# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "abuses", :force => true do |t|
    t.column "v_abused_by", :string
    t.column "abused_user", :integer, :limit => 20
    t.column "e_status",    :string,  :limit => 0,  :default => "pending"
    t.column "v_comment",   :text
  end

  create_table "advertisement_details", :force => true do |t|
    t.column "advid",        :integer, :limit => 10,                 :null => false
    t.column "v_adtitle",    :string,  :limit => 50
    t.column "v_adlink",     :string,  :limit => 50
    t.column "v_adtag",      :string,  :limit => 50
    t.column "v_filename",   :string
    t.column "i_imgwidth",   :integer, :limit => 10
    t.column "i_imgheight",  :integer, :limit => 10
    t.column "i_imgx",       :integer, :limit => 10
    t.column "i_imgy",       :integer, :limit => 10
    t.column "content_type", :string
    t.column "data",         :binary,                :default => "", :null => false
  end

  add_index "advertisement_details", ["advid"], :name => "advertisement_FKIndex1"

  create_table "advertiser_details", :force => true do |t|
    t.column "v_firstname",  :string,                 :default => "", :null => false
    t.column "v_lastname",   :string,                 :default => "", :null => false
    t.column "v_username",   :string,                 :default => "", :null => false
    t.column "v_password",   :string,                 :default => "", :null => false
    t.column "v_company",    :string,                 :default => "", :null => false
    t.column "v_address",    :string,   :limit => 25, :default => "", :null => false
    t.column "v_city",       :string,                 :default => "", :null => false
    t.column "v_state",      :string,                 :default => "", :null => false
    t.column "v_country",    :string,                 :default => "", :null => false
    t.column "v_zip",        :string,                 :default => "", :null => false
    t.column "v_phone",      :string,                 :default => "", :null => false
    t.column "v_email",      :string,                 :default => "", :null => false
    t.column "e_gender",     :string,   :limit => 0,  :default => "", :null => false
    t.column "d_created_at", :datetime
    t.column "d_updated_at", :datetime
    t.column "v_plan",       :string,                 :default => "", :null => false
    t.column "e_status",     :string,   :limit => 0,  :default => "", :null => false
  end

  create_table "bdrb_job_queues", :force => true do |t|
    t.column "args",           :binary
    t.column "worker_name",    :string
    t.column "worker_method",  :string
    t.column "job_key",        :string
    t.column "taken",          :integer
    t.column "finished",       :integer
    t.column "timeout",        :integer
    t.column "priority",       :integer
    t.column "submitted_at",   :datetime
    t.column "started_at",     :datetime
    t.column "finished_at",    :datetime
    t.column "archived_at",    :datetime
    t.column "tag",            :string
    t.column "submitter_info", :string
    t.column "runner_info",    :string
    t.column "worker_key",     :string
  end

  create_table "chapter_comments", :force => true do |t|
    t.column "uid",          :integer,  :limit => 20
    t.column "tag_id",       :integer,  :limit => 20
    t.column "tag_jid",      :integer,                :default => 0
    t.column "v_name",       :string
    t.column "v_e_mail",     :string
    t.column "v_comment",    :text,                   :default => "",        :null => false
    t.column "d_created_on", :datetime,                                      :null => false
    t.column "e_approval",   :string,   :limit => 0,  :default => "pending", :null => false
    t.column "reply",        :string
    t.column "ctype",        :string,                 :default => "chapter"
  end

  create_table "chapter_journals", :force => true do |t|
    t.column "tag_id",        :integer,  :limit => 20
    t.column "v_tag_title",   :string,                 :default => "",        :null => false
    t.column "v_tag_journal", :text,                   :default => "",        :null => false
    t.column "d_created_at",  :datetime,                                      :null => false
    t.column "d_updated_at",  :datetime,                                      :null => false
    t.column "jtype",         :string,                 :default => "chapter", :null => false
  end

  create_table "comments", :force => true do |t|
    t.column "v_name",           :string,               :default => "", :null => false
    t.column "v_email",          :string,               :default => "", :null => false
    t.column "uid",              :integer
    t.column "jid",              :integer
    t.column "v_user_name",      :string
    t.column "v_comment",        :text,                 :default => "", :null => false
    t.column "e_acc_verify",     :string,  :limit => 0, :default => "", :null => false
    t.column "e_aprove_comment", :string,  :limit => 0, :default => "", :null => false
  end

  create_table "exports", :force => true do |t|
    t.column "exported_from", :integer,                                :null => false
    t.column "exported_to",   :integer,                                :null => false
    t.column "exported_id",   :string,  :limit => 256, :default => "", :null => false
    t.column "export_type",   :string,  :limit => 0,   :default => "", :null => false
    t.column "status",        :string,  :limit => 0,   :default => "", :null => false
  end

  create_table "family_friends", :force => true do |t|
    t.column "uid",          :integer, :limit => 100,                        :null => false
    t.column "fid",          :integer, :limit => 100,                        :null => false
    t.column "fnf_category", :integer, :limit => 20
    t.column "status",       :string,  :limit => 0,   :default => "pending", :null => false
    t.column "block_status", :string,  :limit => 0,   :default => "unblock", :null => false
  end

  create_table "faqs", :force => true do |t|
    t.column "question", :string, :default => "", :null => false
    t.column "answer",   :string, :default => "", :null => false
  end

  create_table "fnf_groups", :force => true do |t|
    t.column "fnf_category", :string,  :default => "", :null => false
    t.column "uid",          :integer,                 :null => false
  end

  create_table "galleries", :force => true do |t|
    t.column "v_gallery_name",  :string
    t.column "e_gallery_type",  :string,   :limit => 0
    t.column "d_gallery_date",  :datetime,                                                      :null => false
    t.column "status",          :string,   :limit => 0,   :default => "active"
    t.column "e_gallery_acess", :string,   :limit => 0,   :default => "semiprivate"
    t.column "v_gallery_image", :string,                  :default => "image.png"
    t.column "subchapter_id",   :integer,  :limit => 20,                                        :null => false
    t.column "permissions",     :text,                    :default => "",                       :null => false
    t.column "v_gallery_tags",  :string,   :limit => 512, :default => "Add Tags Here",          :null => false
    t.column "v_desc",          :string,   :limit => 512, :default => "Enter Description Here", :null => false
  end

  create_table "gallery_comments", :force => true do |t|
    t.column "uid",          :integer,  :limit => 20,                         :null => false
    t.column "gallery_id",   :integer,  :limit => 20,                         :null => false
    t.column "gallery_jid",  :integer,  :limit => 20,                         :null => false
    t.column "v_comment",    :text,                    :default => "",        :null => false
    t.column "d_created_on", :datetime,                                       :null => false
    t.column "e_approval",   :string,   :limit => 0,   :default => "pending", :null => false
    t.column "ctype",        :string,   :limit => 250, :default => "gallery", :null => false
    t.column "reply",        :string
  end

  create_table "gallery_journals", :force => true do |t|
    t.column "uid",          :integer,  :limit => 20,                        :null => false
    t.column "galerry_id",   :integer,  :limit => 20,                        :null => false
    t.column "v_title",      :string,                 :default => "",        :null => false
    t.column "v_journal",    :text,                   :default => "",        :null => false
    t.column "d_created_on", :datetime,                                      :null => false
    t.column "d_updated_on", :datetime,                                      :null => false
    t.column "jtype",        :string,                 :default => "gallery", :null => false
  end

  create_table "hmm_users", :force => true do |t|
    t.column "v_fname",        :string,                  :default => "",          :null => false
    t.column "v_lname",        :string,                  :default => "",          :null => false
    t.column "e_sex",          :string,   :limit => 10,  :default => "",          :null => false
    t.column "v_user_name",    :string,                  :default => "",          :null => false
    t.column "v_password",     :string,                  :default => "",          :null => false
    t.column "v_add1",         :string
    t.column "v_add2",         :string
    t.column "v_city",         :string,   :limit => 100
    t.column "v_state",        :string,   :limit => 100
    t.column "v_country",      :string,   :limit => 100, :default => "",          :null => false
    t.column "v_zip",          :string,   :limit => 100, :default => "",          :null => false
    t.column "v_e_mail",       :string,   :limit => 100, :default => "",          :null => false
    t.column "e_user_status",  :string,   :limit => 0,   :default => "unblocked", :null => false
    t.column "i_ip_add",       :integer
    t.column "i_login_status", :integer
    t.column "d_created_date", :datetime,                                         :null => false
    t.column "d_updated_date", :datetime,                                         :null => false
    t.column "d_bdate",        :date,                                             :null => false
    t.column "v_myimage",      :string,   :limit => 100, :default => "blank.jpg"
    t.column "v_security_q",   :string,   :limit => 256, :default => "",          :null => false
    t.column "v_security_a",   :string,   :limit => 256, :default => "",          :null => false
    t.column "v_abt_me",       :text,                    :default => "",          :null => false
    t.column "v_link1",        :string,   :limit => 256, :default => "",          :null => false
    t.column "v_link2",        :string,   :limit => 256, :default => "",          :null => false
    t.column "v_link3",        :string,   :limit => 256, :default => "",          :null => false
  end

  create_table "hmms", :force => true do |t|
    t.column "fname",        :string,                  :default => "",          :null => false
    t.column "lname",        :string,                  :default => "",          :null => false
    t.column "user_name",    :string,                  :default => "",          :null => false
    t.column "password",     :string,                  :default => "",          :null => false
    t.column "add1",         :string,                  :default => "",          :null => false
    t.column "add2",         :string,                  :default => "",          :null => false
    t.column "city",         :string,   :limit => 100, :default => "",          :null => false
    t.column "state",        :string,   :limit => 100, :default => "",          :null => false
    t.column "country",      :string,   :limit => 100, :default => "",          :null => false
    t.column "zip",          :integer,                                          :null => false
    t.column "e-mail",       :string,   :limit => 100, :default => "",          :null => false
    t.column "user_status",  :string,   :limit => 0,   :default => "unblocked", :null => false
    t.column "ip_add",       :integer,                                          :null => false
    t.column "login_status", :boolean,                                          :null => false
    t.column "created_date", :datetime,                                         :null => false
    t.column "updated_date", :datetime,                                         :null => false
  end

  create_table "journals", :force => true do |t|
    t.column "uid",                 :integer,  :limit => 20
    t.column "chap_id",             :integer,  :limit => 20
    t.column "v_title",             :string,                 :default => "", :null => false
    t.column "v_small_description", :string,                 :default => "", :null => false
    t.column "v_large_description", :text,                   :default => "", :null => false
    t.column "d_create_date",       :datetime,                               :null => false
    t.column "d_updated_date",      :datetime,                               :null => false
    t.column "e_journal_access",    :string,   :limit => 0,  :default => "", :null => false
    t.column "d_reminder_date",     :datetime
  end

  create_table "journals_audios", :force => true do |t|
    t.column "v_audio_filename", :string, :limit => 256, :default => "", :null => false
    t.column "v_audio_comment",  :string, :limit => 256
  end

  create_table "journals_comments", :force => true do |t|
    t.column "v_title",          :string,   :limit => 256, :default => "", :null => false
    t.column "v_comment",        :datetime,                                :null => false
    t.column "d_added_date",     :datetime,                                :null => false
    t.column "v_comment_by",     :string,   :limit => 256, :default => "", :null => false
    t.column "v_email_id",       :string,   :limit => 256, :default => "", :null => false
    t.column "e_friend_request", :string,   :limit => 0,   :default => "", :null => false
  end

  create_table "journals_paperworks", :force => true do |t|
    t.column "v_paper_filename", :string, :limit => 256, :default => "", :null => false
    t.column "v_comment",        :string, :limit => 256
  end

  add_index "journals_paperworks", ["v_paper_filename"], :name => "v_paper_filename", :unique => true

  create_table "journals_photos", :force => true do |t|
    t.column "user_content_id", :integer,  :limit => 20,                      :null => false
    t.column "v_title",         :string
    t.column "v_image_comment", :text
    t.column "Comment_from",    :text
    t.column "approved",        :string,   :limit => 0,  :default => "no"
    t.column "date_added",      :datetime
    t.column "jtype",           :string,                 :default => "photo", :null => false
    t.column "updated_date",    :datetime
  end

  create_table "journals_videos", :force => true do |t|
    t.column "v_video_filename", :string,  :limit => 256, :default => "", :null => false
    t.column "v_comment",        :string,  :limit => 256
    t.column "i_video_width",    :integer
    t.column "i_video_height",   :integer
    t.column "i_video_x",        :integer
    t.column "i_video_y",        :integer
  end

  create_table "nonhmm_users", :force => true do |t|
    t.column "uid",       :integer,                 :null => false
    t.column "v_name",    :string,  :default => "", :null => false
    t.column "v_e-mail",  :string,  :default => "", :null => false
    t.column "v_city",    :string
    t.column "v_country", :string
  end

  create_table "pages", :force => true do |t|
    t.column "title",      :string
    t.column "permalink",  :string,   :default => "", :null => false
    t.column "body",       :text
    t.column "created_at", :datetime,                 :null => false
    t.column "updated_at", :datetime,                 :null => false
  end

  create_table "photo_comments", :force => true do |t|
    t.column "uid",             :integer,  :limit => 20
    t.column "journal_id",      :integer,  :limit => 20
    t.column "v_title",         :string
    t.column "v_name",          :string
    t.column "v_uid",           :integer,  :limit => 20
    t.column "v_email",         :string
    t.column "v_comment",       :text
    t.column "d_add_date",      :datetime,                                       :null => false
    t.column "e_approved",      :string,   :limit => 0,   :default => "pending"
    t.column "e_access",        :string,   :limit => 0,   :default => "private"
    t.column "user_content_id", :integer,  :limit => 20,                         :null => false
    t.column "ctype",           :string,   :limit => 250, :default => "moment",  :null => false
    t.column "reply",           :string
  end

  create_table "share_comments", :force => true do |t|
    t.column "name",       :string
    t.column "comment",    :text
    t.column "uid",        :integer,  :limit => 20
    t.column "d_add_date", :datetime
    t.column "share_id",   :integer,  :limit => 20,                        :null => false
    t.column "e_approved", :string,   :limit => 0,  :default => "pending", :null => false
    t.column "reply",      :text
  end

  create_table "share_memories", :force => true do |t|
    t.column "presenter_id", :integer,  :limit => 20,                 :null => false
    t.column "email_list",   :text,                   :default => "", :null => false
    t.column "xml_name",     :string,                 :default => "", :null => false
    t.column "created_date", :datetime,                               :null => false
    t.column "expiry_date",  :datetime,                               :null => false
  end

  create_table "shares", :force => true do |t|
    t.column "presenter_id", :integer,  :limit => 20,                 :null => false
    t.column "email_list",   :string,                 :default => "", :null => false
    t.column "xml_name",     :string,                 :default => "", :null => false
    t.column "created_date", :datetime,                               :null => false
    t.column "expiry_date",  :datetime,                               :null => false
    t.column "guest_name",   :string
    t.column "Visited_date", :datetime
    t.column "message",      :text,                   :default => "", :null => false
    t.column "password",     :string,                 :default => "", :null => false
    t.column "unid",         :string,                 :default => "", :null => false
  end

  create_table "slide_shows", :force => true do |t|
    t.column "img_name", :string, :default => "", :null => false
    t.column "desc",     :text,   :default => "", :null => false
  end

  create_table "sub_chap_journals", :force => true do |t|
    t.column "tag_id",          :integer,  :limit => 20
    t.column "sub_chap_id",     :integer,  :limit => 20,                        :null => false
    t.column "journal_title",   :string,                 :default => "",        :null => false
    t.column "subchap_journal", :text,                   :default => "",        :null => false
    t.column "created_on",      :datetime,                                      :null => false
    t.column "updated_on",      :datetime,                                      :null => false
    t.column "jtype",           :string,                 :default => "subchap", :null => false
  end

  create_table "sub_chapters", :force => true do |t|
    t.column "uid",               :integer,  :limit => 100
    t.column "tagid",             :integer,  :limit => 100
    t.column "sub_chapname",      :string,   :limit => 100
    t.column "status",            :string,   :limit => 0,   :default => "active",                 :null => false
    t.column "v_image",           :string,                  :default => "",                       :null => false
    t.column "permissions",       :text,                    :default => "",                       :null => false
    t.column "e_access",          :string,   :limit => 0,   :default => "semiprivate",            :null => false
    t.column "v_subchapter_tags", :string,   :limit => 512, :default => "Add Tags Here",          :null => false
    t.column "v_desc",            :string,   :limit => 512, :default => "Enter Description Here", :null => false
    t.column "d_created_on",      :datetime,                                                      :null => false
    t.column "d_updated_on",      :datetime,                                                      :null => false
  end

  create_table "subchap_comments", :force => true do |t|
    t.column "uid",          :integer,  :limit => 20
    t.column "subchap_id",   :integer,  :limit => 20,                             :null => false
    t.column "subchap_jid",  :integer,  :limit => 20
    t.column "v_comments",   :text,                    :default => "",            :null => false
    t.column "d_created_on", :datetime,                                           :null => false
    t.column "e_approval",   :string,   :limit => 0,   :default => "pending",     :null => false
    t.column "ctype",        :string,   :limit => 250, :default => "sub_chapter", :null => false
    t.column "reply",        :string
  end

  create_table "tags", :force => true do |t|
    t.column "uid",            :integer
    t.column "sub_chapid",     :integer,  :limit => 100
    t.column "v_tagname",      :string,   :limit => 50,  :default => "",                       :null => false
    t.column "v_chapimage",    :string,   :limit => 100
    t.column "default_tag",    :string,   :limit => 0,   :default => "yes",                    :null => false
    t.column "e_access",       :string,   :limit => 0,   :default => "semiprivate",            :null => false
    t.column "e_visible",      :string,   :limit => 0,   :default => "",                       :null => false
    t.column "d_createddate",  :datetime,                                                      :null => false
    t.column "d_updateddate",  :datetime,                                                      :null => false
    t.column "status",         :string,   :limit => 0,   :default => "active",                 :null => false
    t.column "permissions",    :text,                    :default => "",                       :null => false
    t.column "v_chapter_tags", :string,   :limit => 512, :default => "Add Tags Here",          :null => false
    t.column "v_desc",         :string,   :limit => 512, :default => "Enter Description Here", :null => false
  end

  create_table "tips", :force => true do |t|
    t.column "title",       :string, :default => "", :null => false
    t.column "description", :text,   :default => "", :null => false
  end

  create_table "user_contents", :force => true do |t|
    t.column "gallery_id",    :integer,  :limit => 20,                             :null => false
    t.column "v_tagname",     :string,   :limit => 100, :default => "",            :null => false
    t.column "tagid",         :integer,  :limit => 100,                            :null => false
    t.column "sub_chapid",    :integer,  :limit => 100
    t.column "uid",           :integer,  :limit => 100
    t.column "e_filetype",    :string,   :limit => 0,   :default => "",            :null => false
    t.column "e_access",      :string,   :limit => 0,   :default => "semiprivate", :null => false
    t.column "e_visible",     :string,   :limit => 0,   :default => "no",          :null => false
    t.column "v_filename",    :string,   :limit => 100, :default => "",            :null => false
    t.column "v_desc",        :string,                  :default => "",            :null => false
    t.column "v_tagphoto",    :string,   :limit => 100
    t.column "d_createddate", :datetime,                                           :null => false
    t.column "d_momentdate",  :datetime
    t.column "status",        :string,   :limit => 0,   :default => "active",      :null => false
    t.column "permissions",   :text,                    :default => "",            :null => false
    t.column "views",         :integer,  :limit => 20,  :default => 0,             :null => false
    t.column "flag",          :integer,  :limit => 20
  end

  create_table "user_sessions", :force => true do |t|
    t.column "i_ip_add",     :string
    t.column "uid",          :integer
    t.column "v_user_name",  :string,                :default => "",   :null => false
    t.column "d_date_time",  :datetime,                                :null => false
    t.column "e_logged_in",  :string,   :limit => 0, :default => "no", :null => false
    t.column "e_logged_out", :string,   :limit => 0, :default => "no", :null => false
  end

  create_table "users", :force => true do |t|
    t.column "username",        :string,   :limit => 64
    t.column "email",           :string,   :limit => 128
    t.column "hashed_password", :string,   :limit => 64
    t.column "enabled",         :string,   :limit => 0,   :default => "yes"
    t.column "profile",         :text
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "last_login_at",   :datetime
    t.column "acess_level",     :integer,  :limit => 20,                     :null => false
  end

end
