
development:
    key: 135976accafb191fd1011b7e54183f83
    secret: 277664229757c8ab7363e3ddf9161fcd
    canvas_path: /getinvities/
    callback_path: /path/to/your/callback/
    tunnel:
      username: see.farooq@gmail.com
      host: http://apps.facebook.com/farooqahamed/
      port: 1234
      local_port: 5678

test:
    key: 135976accafb191fd1011b7e54183f83
    secret: 277664229757c8ab7363e3ddf9161fcd
    canvas_path: /getinvities/
    callback_path: /path/to/your/callback/
    tunnel:
      username: see.farooq@gmail.com
      host: http://apps.facebook.com/farooqahamed/
      port: 1234
      local_port: 5678

production:
    key: 135976accafb191fd1011b7e54183f83
    secret: 277664229757c8ab7363e3ddf9161fcd
    canvas_path: /getinvities/
    callback_path: /path/to/your/callback/
    tunnel:
      username: see.farooq@gmail.com
      host: http://apps.facebook.com/farooqahamed/
      port: 1234
      local_port: 5678
